[globals]

;these are global variables
DEBUG=0
UI=app/view/|public/|public/js/
AUTOLOAD=app/controller/|app/model/|util/v3/|api/e-taxware/v5/
CACHE=true
ESCAPE=false

dbserver=mysql:host=127.0.0.1;port=3306;dbname=etaxware
dbuser=root
dbpwd_b64=bXlzcWw=
dbpwd=
dbpwd_env=ETAXWARE_DB_PASSWORD
appdeveloper="e-TaxWare Team"
appdevorg="e-TaxWare Team"
applongname="e-TaxWare"