[routes]

;base routes
GET /blank=BlankController->index
GET /=HomeController->index
GET /dashboard=DashboardController->index
GET|POST /forbidden=AccessController->forbidden
GET|POST /searchoperations=HomeController->searchoperations
GET|POST /listoperations=HomeController->listoperations

;QBO
POST|GET /connectToQb=HomeController->connectToQb

;user routes
GET /login=AuthenticationController->login
POST /authenticate=AuthenticationController->authenticate
GET /logout=AuthenticationController->logout
GET|POST /quickedituser/@id=UserController->quickedit
GET|POST /edituser=UserController->edit
GET|POST /createuser=UserController->add
GET|POST /listusers=UserController->list
GET /viewuser/@id=UserController->view
POST /viewuser=UserController->view
POST /resetaccount=AuthenticationController->resetaccount
POST /resetpassword=AuthenticationController->resetpassword

;api routes
POST /testapi=Api->testapi
POST /sendmail=Api->sendmail
POST /importErpInvoices=Api->importErpInvoices
POST /importErpSalesReceipts=Api->importErpSalesReceipts
POST /importPurchaseOrders=Api->importPurchaseOrders
POST /updateErpInvoices=Api->updateErpInvoices
POST /renewAccessToken=Api->renewAccessToken

;role routes
GET|POST /editrole=RoleController->edit
GET|POST /createrole=RoleController->add
GET|POST /listroles=RoleController->list
GET /viewrole/@id=RoleController->view
POST /viewrole=RoleController->view

;branch routes
GET|POST /editbranch=BranchController->edit
GET|POST /createbranch=BranchController->add
GET|POST /listbranches=BranchController->list
GET /viewbranch/@id=BranchController->view
POST /viewbranch=BranchController->view


;administration routes
GET|POST /administration=AdministrationController->index
POST /edittcsdetails=AdministrationController->edittcsdetails
POST /editcompanydetails=AdministrationController->editcompanydetails
POST /editdevicedetails=AdministrationController->editdevicedetails
GET|POST /efrislogin=AdministrationController->efrislogin
GET|POST /syncefrisbranches=AdministrationController->syncefrisbranches
GET|POST /syncefrisdics=AdministrationController->syncefrisdics
GET|POST /synchscodelist=AdministrationController->synchscodelist
GET|POST /syncefrisexcisedutylist=AdministrationController->syncefrisexcisedutylist
GET|POST /recyclelogs=AdministrationController->recyclelogs
POST /editproductoverridelist=AdministrationController->editproductoverridelist
POST /editenforcetaxexclusionlist=AdministrationController->editenforcetaxexclusionlist

;apikeys
GET|POST /editapikey=ApikeyController->edit
GET|POST /createapikey=ApikeyController->add
GET|POST /listapikeys=ApikeyController->list
GET /viewapikey/@id=ApikeyController->view
POST /viewapikey=ApikeyController->view

;settings routes
GET|POST /setting=SettingController->index
GET|POST /editsettings=SettingController->edit

;report routes
GET|POST /report=ReportController->index
GET|POST /listreportgroups=ReportController->listreportgroups
GET|POST /listreports=ReportController->listreports
GET|POST /runreport=ReportController->runreport

;events routes
GET|POST /listevents=EventController->listevents
GET|POST /etaxware/listevents=EventController->listevents

GET|POST /listeventnotificationtypes=EventController->listeventnotificationtypes
GET|POST /etaxware/listeventnotificationtypes=EventController->listeventnotificationtypes

GET|POST /listeventnotifications=EventController->listeventnotifications
GET|POST /etaxware/listeventnotifications=EventController->listeventnotifications

;notification routes
GET|POST /listnotifications=NotificationController->listnotifications
GET|POST /etaxware/listnotifications=NotificationController->listnotifications
GET|POST /readnotification=NotificationController->readnotification
GET|POST /etaxware/readnotification=NotificationController->readnotification

;Email
POST /sendmail=Api->sendmail
POST /sendinappnotification=Api->sendinappnotification
POST /logemailnotification=Api->logemailnotification

;currency routes
GET|POST /currency=CurrencyController->index
GET|POST /editcurrency=CurrencyController->edit
GET|POST /createcurrency=CurrencyController->add
GET|POST /listcurrencies=CurrencyController->list
GET /viewcurrency/@id=CurrencyController->view
POST /viewcurrency=CurrencyController->view
POST /fetchcurrencyrates=CurrencyController->fetchcurrencyrates

;product routes
GET|POST /product=ProductController->index
GET|POST /editproduct=ProductController->edit
GET|POST /createproduct=ProductController->add
GET|POST /listproducts=ProductController->list
GET|POST /etaxware/listproducts=ProductController->list
GET /viewproduct/@id=ProductController->view
POST /viewproduct=ProductController->view
POST /uploadproduct=ProductController->uploadproduct
POST /stockin=ProductController->stockin
POST /fetchproduct=ProductController->fetchproduct
POST /stockout=ProductController->stockout
GET|POST /searchmeasureunits=ProductController->searchmeasureunits
GET|POST /etaxware/searchmeasureunits=ProductController->searchmeasureunits
GET|POST /searchproducts=ProductController->searchproducts
GET|POST /etaxware/searchproducts=ProductController->searchproducts
; 2026-04-11 19:44:49 +03:00 - Currency search endpoint for Product Select2 currency field.
GET|POST /searchcurrencies=ProductController->searchcurrencies
GET|POST /etaxware/searchcurrencies=ProductController->searchcurrencies
GET|POST /searchcommoditycodes=ProductController->searchcommoditycodes
GET|POST /etaxware/searchcommoditycodes=ProductController->searchcommoditycodes
GET|POST /searchexcisedutycodes=ProductController->searchexcisedutycodes
GET|POST /etaxware/searchexcisedutycodes=ProductController->searchexcisedutycodes
GET|POST /syncproducts=ProductController->syncproducts
GET|POST /listotherunits=ProductController->listotherunits
GET|POST /etaxware/listotherunits=ProductController->listotherunits
GET|POST /etaxware/addotherunits=ProductController->addotherunits
GET|POST /addotherunits=ProductController->addotherunits
GET|POST /deleteotherunits=ProductController->deleteotherunits
GET|POST /editotherunits=ProductController->editotherunits
GET|POST /stocktransfer=ProductController->stocktransfer
GET|POST /stockqueryproduct=ProductController->stockquery
GET|POST /liststocktransfers=ProductController->liststocktransfers
GET|POST /liststockadjustments=ProductController->liststockadjustments
GET|POST /downloadstockadjustments=ProductController->downloadstockadjustments
GET|POST /downloadErpProducts=ProductController->downloadErpProducts
POST /fetchErpproduct=ProductController->fetchErpproduct
POST|GET /uploadOpeningStock=ProductController->uploadOpeningStock
POST|GET /etaxware/uploadOpeningStock=ProductController->uploadOpeningStock
GET|POST /listfiles=ProductController->listfiles
GET|POST /downloadfilelist=ProductController->downloadfilelist
GET|POST /listopeningstockprocruns=ProductController->listopeningstockprocruns
GET|POST /listopeningstockproclogs=ProductController->listopeningstockproclogs
GET|POST|PUT /uploadfiletofilesystem=ProductController->uploadfiletofilesystem
GET|POST /openingstockproc/@id=ProductController->openingstockproc
GET|POST /etaxware/openingstockproc/@id=ProductController->openingstockproc
GET|POST /archivefile/@id=ProductController->archivefile
GET|POST /downloadopeningstockprocrpt/@id=ProductController->downloadopeningstockprocrpt
GET|POST /subfolderlist=ProductController->subfolderlist
GET|POST /viewfile/@id=ProductController->viewfile
GET|POST /exportproducts=ProductController->exportproducts
GET|POST /etaxware/exportproducts=ProductController->exportproducts
GET|POST /searchhscodes=ProductController->searchhscodes
GET|POST /etaxware/searchhscodes=ProductController->searchhscodes
GET|POST /searchexportmeasureunits=ProductController->searchexportmeasureunits
GET|POST /etaxware/searchexportmeasureunits=ProductController->searchexportmeasureunits

;commodity codes routes
GET|POST /commoditycode=CommoditycodeController->index
GET|POST /fetchcommoditycode=CommoditycodeController->fetchcommoditycode
GET|POST /etaxware/fetchcommoditycode=CommoditycodeController->fetchcommoditycode
GET|POST /etaxware/getcommoditycode=CommoditycodeController->getcommoditycode
GET|POST /getcommoditycode=CommoditycodeController->getcommoditycode

;invoice routes
GET|POST /invoice=InvoiceController->index
GET|POST /editinvoice=InvoiceController->edit
GET|POST /createinvoice=InvoiceController->add
GET|POST /listinvoices=InvoiceController->list
GET|POST /etaxware/listinvoices=InvoiceController->list
GET /viewinvoice/@id=InvoiceController->view
POST /viewinvoice=InvoiceController->view
POST /uploadinvoice=InvoiceController->uploadinvoice
POST /downloadinvoice=InvoiceController->downloadinvoice
GET|POST /printinvoice=InvoiceController->printinvoice
GET|POST /printinvoice/@id=InvoiceController->printinvoice
GET|POST /pviewinvoice/@id=InvoiceController->pviewinvoice
GET|POST /syncefrisinvoices=InvoiceController->syncefrisinvoices
GET|POST /downloadErpInvoices=InvoiceController->downloadErpInvoices
POST /fetchErpInvoice=InvoiceController->fetchErpInvoice
POST /updateErpInvoice=InvoiceController->updateErpInvoice
GET|POST /searchinvoices=InvoiceController->searchinvoices
GET|POST /etaxware/searchinvoices=InvoiceController->searchinvoices
GET|POST /searchinvoicetypes=InvoiceController->searchinvoicetypes
GET|POST /etaxware/searchinvoicetypes=InvoiceController->searchinvoicetypes
GET|POST /searchinvoicekinds=InvoiceController->searchinvoicekinds
GET|POST /etaxware/searchinvoicekinds=InvoiceController->searchinvoicekinds
GET|POST /searchdatasources=InvoiceController->searchdatasources
GET|POST /etaxware/searchdatasources=InvoiceController->searchdatasources
GET|POST /searchindustries=InvoiceController->searchindustries
GET|POST /etaxware/searchindustries=InvoiceController->searchindustries
GET|POST /searchdeliveryterms=InvoiceController->searchdeliveryterms
GET|POST /etaxware/searchdeliveryterms=InvoiceController->searchdeliveryterms
GET|POST /previewinvoiceexcise=InvoiceController->previewinvoiceexcise
GET|POST /etaxware/previewinvoiceexcise=InvoiceController->previewinvoiceexcise

;Goods
GET|POST /listgoods=GoodController->list
GET|POST /etaxware/listgoods=GoodController->list

;Taxes
GET|POST /listtaxes=TaxController->list
GET|POST /etaxware/listtaxes=TaxController->list
GET|POST /listtaxtypes=TaxController->listtaxtypes
GET|POST /etaxware/listtaxtypes=TaxController->listtaxtypes

;Payments
GET|POST /listpayments=PaymentController->list
GET|POST /etaxware/listpayments=paymentController->list

;credit note routes
GET|POST /creditnote=CreditnoteController->index
GET|POST /editcreditnote=CreditnoteController->edit
GET|POST /createcreditnote=CreditnoteController->add
GET|POST /listcreditnotes=CreditnoteController->list
GET|POST /etaxware/listcreditnotes=CreditnoteController->list
GET /viewcreditnote/@id=CreditnoteController->view
POST /viewcreditnote=CreditnoteController->view
POST /uploadcreditnote=CreditnoteController->uploadcreditnote
POST /downloadcreditnote=CreditnoteController->downloadcreditnote
GET|POST /printcreditnote=CreditnoteController->printcreditnote
GET|POST /printcreditnote/@id=CreditnoteController->printcreditnote
GET|POST /pviewcreditnote/@id=CreditnoteController->pviewcreditnote
POST /approvecreditnote=CreditnoteController->approvecreditnote
POST /cancelcreditnote=CreditnoteController->cancelcreditnote
POST /syncefriscreditnotes=CreditnoteController->syncefriscreditnotes
GET|POST /downloadErpCreditnotes=CreditnoteController->downloadErpCreditnotes
POST /fetchErpCreditnote=CreditnoteController->fetchErpCreditnote
GET|POST /searchcdnotereasoncodes=CreditnoteController->searchcdnotereasoncodes
GET|POST /etaxware/searchcdnotereasoncodes=CreditnoteController->searchcdnotereasoncodes
GET|POST /previewcreditnoteexcise=CreditnoteController->previewcreditnoteexcise
GET|POST /etaxware/previewcreditnoteexcise=CreditnoteController->previewcreditnoteexcise

;debit note routes
GET|POST /debitnote=DebitnoteController->index
GET|POST /editdebitnote=DebitnoteController->edit
GET|POST /createdebitnote=DebitnoteController->add
GET|POST /listdebitnotes=DebitnoteController->list
GET|POST /etaxware/listdebitnotes=DebitnoteController->list
GET /viewdebitnote/@id=DebitnoteController->view
POST /viewdebitnote=DebitnoteController->view
POST /uploaddebitnote=DebitnoteController->uploaddebitnote
POST /downloaddebitnote=DebitnoteController->downloaddebitnote
GET|POST /printdebitnote=DebitnoteController->printdebitnote
GET|POST /printdebitnote/@id=DebitnoteController->printdebitnote
GET|POST /pviewdebitnote/@id=DebitnoteController->pviewdebitnote
POST /approvedebitnote=DebitnoteController->approvedebitnote
POST /canceldebitnote=DebitnoteController->canceldebitnote
POST /syncefrisdebitnotes=DebitnoteController->syncefrisdebitnotes
GET|POST /downloadErpDebitnotes=CreditnoteController->downloadErpDebitnotes
POST /fetchErpDebitnote=CreditnoteController->fetchErpDebitnote
GET|POST /searchdebitnotereasoncodes=DebitnoteController->searchdebitnotereasoncodes
GET|POST /etaxware/searchdebitnotereasoncodes=DebitnoteController->searchdebitnotereasoncodes
GET|POST /previewdebitnoteexcise=DebitnoteController->previewdebitnoteexcise
GET|POST /etaxware/previewdebitnoteexcise=DebitnoteController->previewdebitnoteexcise

;Tax Payer routes
GET|POST /querytaxpayer=TaxPayerController->querytaxpayer
GET|POST /etaxware/querytaxpayer=TaxPayerController->querytaxpayer


;customer routes
GET|POST /customer=CustomerController->index
GET|POST /editcustomer=CustomerController->edit
GET|POST /createcustomer=CustomerController->add
GET|POST /listcustomers=CustomerController->list
GET /viewcustomer/@id=CustomerController->view
POST /viewcustomer=CustomerController->view
POST /checkcustomer=CustomerController->checkcustomer

GET|POST /downloadErpCustomers=CustomerController->downloadErpCustomers
POST /fetchErpCustomer=CustomerController->fetchErpCustomer

;supplier routes
GET|POST /supplier=SupplierController->index
GET|POST /editsupplier=SupplierController->edit
GET|POST /createsupplier=SupplierController->add
GET|POST /listsuppliers=SupplierController->list
GET /viewsupplier/@id=SupplierController->view
POST /viewsupplier=SupplierController->view
POST /checksupplier=SupplierController->checksupplier
GET|POST /downloadErpSuppliers=SupplierController->downloadErpSuppliers
POST /fetchErpSupplier=SupplierController->fetchErpSupplier

;purchaseorder routes
GET|POST /purchaseorder=PurchaseorderController->index
GET|POST /createpurchaseorder=PurchaseorderController->add
GET|POST /listpurchaseorders=PurchaseorderController->list
GET /viewpurchaseorder/@id=PurchaseorderController->view
POST /viewpurchaseorder=PurchaseorderController->view
GET|POST /downloadErpPurchaseorders=PurchaseorderController->downloadErpPurchaseorders
POST /fetchErpPurchaseorder=PurchaseorderController->fetchErpPurchaseorder
POST /uploadpurchaseorder=PurchaseorderController->uploadpurchaseorder
